### ISSUE TITLE
onRestoreInstanceState IllegalArgumentException

### ISSUE THREAD

**Issue by nextflex** [oli107/material-range-bar#81]
I get this crash report from a Android 5.1 device (Xperia ZR). I think it's a problem with onRestoreInstanceState in Fragments. Any ideas?

java.lang.IllegalArgumentException: Pin index left 0, or right 31 is out of bounds. Check that it is greater than the minimum (100.0) and less than the maximum value (250.0)
	at com.appyvet.rangebar.RangeBar.setRangePinsByIndices(RangeBar.java)
	                                 setRangePinsByValue(RangeBar.java)
	                                 rangeBarInit(RangeBar.java)
	                                 createBar(RangeBar.java)
	                                 isValidTickCount(RangeBar.java)
	                                 onActionMove(RangeBar.java)
	                                 pressPin(RangeBar.java)
	                                 movePin(RangeBar.java)
	                                 access$002(RangeBar.java)
	                                 access$000(RangeBar.java)
	at com.appyvet.rangebar.RangeBar.onRestoreInstanceState(RangeBar.java)
	at android.view.View.dispatchRestoreInstanceState(View.java:13823)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2894)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2894)
	at android.view.View.restoreHierarchyState(View.java:13801)
	at android.support.v4.app.Fragment.restoreViewState(Fragment.java)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java)
	at android.support.v4.view.ViewPager.populate(ViewPager.java)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java)
	at com.astuetz.PagerSlidingTabStrip$2.onClick(PagerSlidingTabStrip.java)
	at android.view.View.performClick(View.java:4856)
	at android.view.View$PerformClick.run(View.java:19956)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5389)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by candeiasdan** [comment]
any update on this issue?
